### PR TITLE
Arena Reward

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
- Closes https://github.com/azerothcore/mod-bg-reward/issues/10

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Winfidonarleyan** [comment]
:/

**Comment by Helias** [comment]
@Winfidonarleyan, is a problem? xD :P
it's just adding a feature

**Comment by Winfidonarleyan** [comment]
I don't like the code refactor

**Comment by Mamaro89** [comment]
It workd perfectly now.. Great

**Pull request merged**
